### ISSUE TITLE
model in onedrive can not reached

### ISSUE THREAD

**Issue by MichaelFan01** [nobukatsu-kajiura/Self-Play-RL#1]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/49156452/154897917-2f7a3909-23e8-4472-bd5c-41099132768d.png">
The models link can not connected, can you upload a new one?

**Comment by nobukatsu-kajiura** [comment]
Thank you for the notice. I double-checked that it was possible to access OneDrive even in chrome incognito mode. Please check your browser environment again. If you can't access it, I'll share it in another way.
